# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'seg_tongue_work.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1592, 911)
        MainWindow.setStyleSheet("background-image:url(F:/PythonWorkspace/unet_keras/back2.jpg)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.loadtongue = QtWidgets.QPushButton(self.centralwidget)
        self.loadtongue.setGeometry(QtCore.QRect(180, 420, 180, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.loadtongue.setFont(font)
        self.loadtongue.setStyleSheet("    border:1px solid #717171;\n"
"    border-radius:5px;\n"
"    background-color:rgb(160, 255, 174)\n"
"")
        self.loadtongue.setObjectName("loadtongue")
        self.uesr_tongue = QtWidgets.QLabel(self.centralwidget)
        self.uesr_tongue.setGeometry(QtCore.QRect(90, 10, 400, 400))
        self.uesr_tongue.setStyleSheet("\n"
"\n"
"    border:1px solid #717171;\n"
"    border-radius:5px;")
        self.uesr_tongue.setText("")
        self.uesr_tongue.setObjectName("uesr_tongue")
        self.segtongue = QtWidgets.QPushButton(self.centralwidget)
        self.segtongue.setGeometry(QtCore.QRect(1190, 420, 180, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.segtongue.setFont(font)
        self.segtongue.setStyleSheet("    border:1px solid #717171;\n"
"    border-radius:5px;\n"
"    background-color:rgb(160, 255, 174)\n"
"")
        self.segtongue.setObjectName("segtongue")
        self.segoutput = QtWidgets.QLabel(self.centralwidget)
        self.segoutput.setGeometry(QtCore.QRect(1080, 10, 400, 400))
        self.segoutput.setStyleSheet("    border:1px solid #717171;\n"
"    border-radius:5px;\n"
"    background-color:rgb(160, 255, 174)\n"
"")
        self.segoutput.setText("")
        self.segoutput.setObjectName("segoutput")
        self.tongue_colorButton = QtWidgets.QPushButton(self.centralwidget)
        self.tongue_colorButton.setGeometry(QtCore.QRect(80, 480, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tongue_colorButton.setFont(font)
        self.tongue_colorButton.setStyleSheet("border:1px solid #717171;\n"
"    border-radius:5px;\n"
"background-image:url(F:/PythonWorkspace/unet_keras/back2.jpg)")
        self.tongue_colorButton.setObjectName("tongue_colorButton")
        self.tai_colorButton = QtWidgets.QPushButton(self.centralwidget)
        self.tai_colorButton.setGeometry(QtCore.QRect(81, 560, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tai_colorButton.setFont(font)
        self.tai_colorButton.setStyleSheet("    \n"
"    border:1px solid #717171;\n"
"    border-radius:5px;")
        self.tai_colorButton.setObjectName("tai_colorButton")
        self.tongue_shapeButton = QtWidgets.QPushButton(self.centralwidget)
        self.tongue_shapeButton.setGeometry(QtCore.QRect(80, 640, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tongue_shapeButton.setFont(font)
        self.tongue_shapeButton.setStyleSheet("    \n"
"    border:1px solid #717171;\n"
"    border-radius:5px;\n"
"")
        self.tongue_shapeButton.setObjectName("tongue_shapeButton")
        self.suggestionBtn = QtWidgets.QPushButton(self.centralwidget)
        self.suggestionBtn.setGeometry(QtCore.QRect(570, 480, 161, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.suggestionBtn.setFont(font)
        self.suggestionBtn.setStyleSheet("    border:1px solid #717171;\n"
"    border-radius:5px;\n"
"    background-color:rgb(160, 255, 174)\n"
"")
        self.suggestionBtn.setObjectName("suggestionBtn")
        self.tongue_color = QtWidgets.QLabel(self.centralwidget)
        self.tongue_color.setGeometry(QtCore.QRect(250, 480, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tongue_color.setFont(font)
        self.tongue_color.setStyleSheet("    border:1px solid #717171;\n"
"    border-radius:5px;\n"
"    background-color:rgb(160, 255, 174)\n"
"")
        self.tongue_color.setText("")
        self.tongue_color.setObjectName("tongue_color")
        self.tai_color = QtWidgets.QLabel(self.centralwidget)
        self.tai_color.setGeometry(QtCore.QRect(250, 560, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tai_color.setFont(font)
        self.tai_color.setStyleSheet("    border:1px solid #717171;\n"
"    border-radius:5px;\n"
"    background-color:rgb(160, 255, 174)\n"
"")
        self.tai_color.setText("")
        self.tai_color.setObjectName("tai_color")
        self.tongue_shape = QtWidgets.QLabel(self.centralwidget)
        self.tongue_shape.setGeometry(QtCore.QRect(250, 640, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tongue_shape.setFont(font)
        self.tongue_shape.setStyleSheet("    border:1px solid #717171;\n"
"    border-radius:5px;\n"
"    background-color:rgb(160, 255, 174)\n"
"")
        self.tongue_shape.setText("")
        self.tongue_shape.setObjectName("tongue_shape")
        self.tongue_shapeButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.tongue_shapeButton2.setGeometry(QtCore.QRect(80, 720, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tongue_shapeButton2.setFont(font)
        self.tongue_shapeButton2.setStyleSheet("    border:1px solid #717171;\n"
"    border-radius:5px;\n"
"    background-color:rgb(160, 255, 174)\n"
"")
        self.tongue_shapeButton2.setObjectName("tongue_shapeButton2")
        self.tongue_shape2 = QtWidgets.QLabel(self.centralwidget)
        self.tongue_shape2.setGeometry(QtCore.QRect(250, 720, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tongue_shape2.setFont(font)
        self.tongue_shape2.setStyleSheet("    border:1px solid #717171;\n"
"    border-radius:5px;\n"
"    background-color:rgb(160, 255, 174)\n"
"")
        self.tongue_shape2.setText("")
        self.tongue_shape2.setObjectName("tongue_shape2")
        self.tongue_shapeButton3 = QtWidgets.QPushButton(self.centralwidget)
        self.tongue_shapeButton3.setGeometry(QtCore.QRect(80, 800, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tongue_shapeButton3.setFont(font)
        self.tongue_shapeButton3.setStyleSheet("    border:1px solid #717171;\n"
"    border-radius:5px;\n"
"    background-color:rgb(160, 255, 174)\n"
"")
        self.tongue_shapeButton3.setObjectName("tongue_shapeButton3")
        self.tongue_shape3 = QtWidgets.QLabel(self.centralwidget)
        self.tongue_shape3.setGeometry(QtCore.QRect(250, 800, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tongue_shape3.setFont(font)
        self.tongue_shape3.setStyleSheet("    border:1px solid #717171;\n"
"    border-radius:5px;\n"
"    background-color:rgb(160, 255, 174)\n"
"")
        self.tongue_shape3.setText("")
        self.tongue_shape3.setObjectName("tongue_shape3")
        self.tongue_recognition = QtWidgets.QLabel(self.centralwidget)
        self.tongue_recognition.setGeometry(QtCore.QRect(570, 10, 400, 400))
        self.tongue_recognition.setStyleSheet("    border:1px solid #717171;\n"
"    border-radius:5px;\n"
"    background-color:rgb(160, 255, 174)\n"
"")
        self.tongue_recognition.setText("")
        self.tongue_recognition.setObjectName("tongue_recognition")
        self.tongue_recoButton = QtWidgets.QPushButton(self.centralwidget)
        self.tongue_recoButton.setGeometry(QtCore.QRect(680, 420, 180, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tongue_recoButton.setFont(font)
        self.tongue_recoButton.setStyleSheet("    border:1px solid #717171;\n"
"    border-radius:5px;\n"
"    background-color:rgb(160, 255, 174)\n"
"")
        self.tongue_recoButton.setObjectName("tongue_recoButton")
        self.sugtext = QtWidgets.QTextBrowser(self.centralwidget)
        self.sugtext.setGeometry(QtCore.QRect(570, 520, 401, 331))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sugtext.setFont(font)
        self.sugtext.setStyleSheet("border:1px solid #717171;\n"
"    border-radius:5px;\n"
"background-image:url(F:/PythonWorkspace/unet_keras/back2.jpg);")
        self.sugtext.setObjectName("sugtext")
        self.esophagus_btn = QtWidgets.QPushButton(self.centralwidget)
        self.esophagus_btn.setGeometry(QtCore.QRect(1080, 480, 171, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.esophagus_btn.setFont(font)
        self.esophagus_btn.setStyleSheet("border:1px solid #717171;\n"
"    border-radius:5px;")
        self.esophagus_btn.setObjectName("esophagus_btn")
        self.esophagus_sug = QtWidgets.QTextBrowser(self.centralwidget)
        self.esophagus_sug.setGeometry(QtCore.QRect(1080, 520, 401, 331))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.esophagus_sug.setFont(font)
        self.esophagus_sug.setStyleSheet("border:1px solid #717171;\n"
"    border-radius:5px;\n"
"")
        self.esophagus_sug.setObjectName("esophagus_sug")
        self.back_btn = QtWidgets.QPushButton(self.centralwidget)
        self.back_btn.setGeometry(QtCore.QRect(1510, 840, 75, 23))
        self.back_btn.setObjectName("back_btn")
        self.uesr_tongue.raise_()
        self.loadtongue.raise_()
        self.segtongue.raise_()
        self.segoutput.raise_()
        self.tongue_colorButton.raise_()
        self.tai_colorButton.raise_()
        self.tongue_shapeButton.raise_()
        self.suggestionBtn.raise_()
        self.tongue_color.raise_()
        self.tai_color.raise_()
        self.tongue_shape.raise_()
        self.tongue_shapeButton2.raise_()
        self.tongue_shape2.raise_()
        self.tongue_shapeButton3.raise_()
        self.tongue_shape3.raise_()
        self.tongue_recognition.raise_()
        self.tongue_recoButton.raise_()
        self.sugtext.raise_()
        self.esophagus_btn.raise_()
        self.esophagus_sug.raise_()
        self.back_btn.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1592, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "欢迎来到智能舌诊系统！"))
        self.loadtongue.setText(_translate("MainWindow", "上传舌象"))
        self.segtongue.setText(_translate("MainWindow", "舌体分割"))
        self.tongue_colorButton.setText(_translate("MainWindow", "舌色分析"))
        self.tai_colorButton.setText(_translate("MainWindow", "苔色分析"))
        self.tongue_shapeButton.setText(_translate("MainWindow", "胖瘦舌分析"))
        self.suggestionBtn.setText(_translate("MainWindow", "初步诊断"))
        self.tongue_shapeButton2.setText(_translate("MainWindow", "裂纹舌分析"))
        self.tongue_shapeButton3.setText(_translate("MainWindow", "齿痕舌分析"))
        self.tongue_recoButton.setText(_translate("MainWindow", "舌象检测"))
        self.esophagus_btn.setText(_translate("MainWindow", "食管癌诊断"))
        self.back_btn.setText(_translate("MainWindow", "返回"))
